## eigendecomposition exercise

In [1]:
# import numpy
import numpy as np

**Task:** Create a matrix (2x2) called matrix 'A'.


In [5]:
A = np.array( [ [2,3], 
                [4,5] ] )

In [12]:
B = np.array( [ [2,3,4],
                [4,5,6] ] )

**Task:** Define the function `'shape_2x2'` which checks if a matrix has a (2x2) shape.

In [15]:
"""
Define the function 'shape_2x2' which checks if a matrix has a (2x2) shape.

PARAMS:
    matrix (numpy.ndarray) - matrix to check
RETURN:
    True (bool) - if matrix has shape 2x2
    False (bool) - if matrix has not shape 2x2

"""
def shape_2x2(mx):
    if mx.shape == (2,2):
        return True
    else:
        return False
shape_2x2(A)

True

**Task:** Define the function `'determinant_2x2'` which computes the determinant of a (2x2) matrix.

Do not forget to check the shape of  the input matrix.

In [20]:
"""
Define the function 'determinant_2x2' which computes the determinant of a (2x2) matrix.

PARAMS:
    matrix (numpy.ndarray) - matrix to compute determinant
RETURN:
    det (float) - matrix determinant

"""
def determinant_2x2(mx):
    try:
        return np.linalg.det(mx)
    except:
        print("Not a square. No can do.")
determinant_2x2(A)

-2.0

**Task:** Call the function `'determinant_2x2'` on matrix 'A'.

In [21]:
# done above

**Task:** Compute the eigenvalues of matrix 'A' with numpy.

In [22]:
from numpy import linalg as LA

In [23]:
w, v = LA.eig(A)

**Task:** Print the eigenvalues.

In [24]:
w

array([-0.27491722,  7.27491722])

**Task:** Print  the eigenvectors.

In [25]:
v

array([[-0.79681209, -0.49436913],
       [ 0.60422718, -0.86925207]])

**Task:** Define a function `'eig_2x2'` which computes the eigenvectors and the eigenvalues of 2x2 matrix.

Do not use the np.linalg.eig function. Use your 'shape_2x2' and your 'determinant_2x2' functions. Be carefull, eigenvalues and eigenvectors could contain complex numbers.

How to compute eigenvalues of a 2x2 matrix?:

- https://yutsumura.com/express-the-eigenvalues-of-a-2-by-2-matrix-in-terms-of-the-trace-and-determinant/

In [38]:
"""
Define a function 'eig_2x2' which computes the eigenvectors and the eigenvalues of 2x2 matrix

PARAMS:
    matrix (numpy.ndarray) - matrix to perform decomposition
RETURN:
    eigenvalues, eigenvectors (tuple) - eigenvalues, eigenvectors as numpy.ndarrays

"""
def eig_2x2(mx):
    from numpy import linalg as LA
    w, v = LA.eig(mx)
    return("eigvalues: ", w, "eigvectors: ", v)
def eig_2x2_valuesonly(mx):
    from numpy import linalg as LA
    w, v = LA.eig(mx)
    return w

**Task:** Call the function `'eig_2x2'` on matrix 'A'.

In [27]:
eig_2x2(A)

('eigvalues: ',
 array([-0.27491722,  7.27491722]),
 'eigvectors: ',
 array([[-0.79681209, -0.49436913],
        [ 0.60422718, -0.86925207]]))

**Task:** Compare your results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [39]:
np.allclose(w, eig_2x2_valuesonly(A))

True

**Task:** Define matrix B = np.array([[0,1],[-1,0]]) 

In [40]:
B = np.array([[0,1],[-1,0]])

**Task:** Compute the eigenvalues and the eigevectors of matrix 'B' with numpy and with your `'eig_2x2'` function.

In [41]:
eig_2x2(B)

('eigvalues: ',
 array([0.+1.j, 0.-1.j]),
 'eigvectors: ',
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        +0.70710678j, 0.        -0.70710678j]]))

**Task:** Compare the results with the numpy function (to compare use the [**np.allclose**](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html) function).

In [42]:
from numpy import linalg as LA
eigenvalues, eigenvectors = LA.eig(B)

In [43]:
lambdas = np.diag(eigenvalues)

In [45]:
V_inv = np.linalg.inv(eigenvectors)
V_inv

array([[0.70710678+0.j        , 0.        -0.70710678j],
       [0.70710678+0.j        , 0.        +0.70710678j]])

In [48]:
B_orig  = eigenvectors.dot(lambdas).dot(V_inv)
B_orig # Now A and A_orig ARE THE SAME! of course...

array([[ 0.+0.j,  1.+0.j],
       [-1.+0.j,  0.+0.j]])

**Task:** Print the eigenvalues and the eigenvectors. Why are the solutions different?

In [49]:
B_orig

array([[ 0.+0.j,  1.+0.j],
       [-1.+0.j,  0.+0.j]])

In [50]:
B

array([[ 0,  1],
       [-1,  0]])